### ISSUE TITLE
Watch the backup dir and upload automatically

### ISSUE THREAD

**Issue by d0ugal** [d0ugal/hassio-dropbox-upload#3]
Just an idea, but this would be quicker.

It would mean the container would always run.

**Comment by d0ugal** [comment]
We should do this. Using [watchdog](https://pythonhosted.org/watchdog/) to track for new files and trigger the backup.

The overhead should be minimal, so I think it is the best option.

**Comment by IoTmessenger** [comment]
Would be a very helpful addition, also for logging/debugging purposes because the addon is then always running. Currently there is no way to check logs. Only errors show up in my case.

I use Node-red to have scheduled backups (full snapshot once a week and daily partial snapshots). As a workaround, I currently use a timer node to start your addon when 10 minutes have passed since creation of a snapshot.

**Comment by d0ugal** [comment]
This was done here: https://github.com/d0ugal/hassio-dropbox-upload/commit/694c3800d5d523ad925cd9bf01583f48e294dba0

I went for a simpler method than watchdog, maybe I can expand it later.
