### ISSUE TITLE
Dropbox upload container won't start with exit code 139

### ISSUE THREAD

**Issue by jshrack-ssi** [d0ugal/hassio-dropbox-upload#56]
I noticed the dropbox upload container is not starting with exit code 139. No additional logs are generated by the container at all. This behavior is recent with no prior case of this behavior. The plugin has been reinstalled to no avail. The plugin version is 1.14, Supervisor 155, HassOS 2.11. Thoughts or insights?

**Comment by davidclemens** [comment]
I second that.

Home Assistant: 0.106.6
Supervisor: 209
HassOS 3.12 on a RPi 3B+

I hope this is an easy fix for you @d0ugal.
Thanks for your work!

**Comment by d0ugal** [comment]
I don’t know how to fix this or reproduce this problem. It’s been working flawlessly for me and this is only the second report I have had of this error.

Any other details you can give?

**Comment by d0ugal** [comment]
FWIW I am running the same version Home Assistant and the same supervisor version.

You however are on a raspberry pi, I am not. I wonder if that could be the problem and it’s something related to arm?

**Comment by davidclemens** [comment]
Wow thanks for the quick response.

Sure more details:
- I have the 64bit Home Assistant image for RPi3B+ installed
- I boot off a 120 GB SSD connected via USB to the RPi
- On Dropbox I created an App with full dropbox access. The token worked flawlessly with the Dropbox Sync addon by @danielwelch. But I really need the functionality of yours that older snapshots are deleted on Dropbox as well.
- my configuration is the following:
     `access_token: <TOKEN>`
     `dropbox_dir: /Level1/Level2/Level3/`
     `keep: 32`
     `mins_between_backups: 60`
     `filename: snapshot_name`
     `debug: true`
- when I start the addon, the wheel in the `Start` button spins a couple of seconds, then it looks as if it started, since the buttons `Uninstall`, `Restart` and `Stop` show up. Also the grey dot next to the addon version turns green. However there are no logs even after refreshing. And if I return to the Supervisor dashboard the symbol is also green, suggesting it's running. But if I click again on the Dropbox Upload addon, it shows up as stopped.
- The System Log shows the following relevant entries:

```
20-03-15 12:54:42 INFO (SyncWorker_8) [supervisor.docker.addon] Start Docker add-on d0ugal/hassio-dropbox-upload-aarch64 with version 1.1.4
20-03-15 13:18:40 INFO (SyncWorker_1) [supervisor.docker.interface] Clean addon_8aef3602_dropbox_upload application
```
- This suggests that it tries to start up for about 24 minutes!?
- I restarted Home Assistant and HassOS

I don't know what else could be relevant. Is there a way to get the docker logs?

Edit:
> You however are on a raspberry pi, I am not. I wonder if that could be the problem and it’s something related to arm?

That could be the case but I'm not advanced enough to know how this could be relevant.

Thanks a lot for your quick help!

**Comment by d0ugal** [comment]
Is there anything in the log below the add on config?

**Comment by davidclemens** [comment]
Sadly not. Its really hard to get a lead on this.

**Comment by davidclemens** [comment]
Update:
Now it works for me as well. I'm not sure what did it.
After I entirely restarted the RPi, I started the addon via ssh in the terminal and then it worked. Maybe it needed the entire system restart, not just Home Assistant or HassOS...

Frustrating to not being able to nail the problem down.

Thanks again for your prompt assistance!

**Comment by d0ugal** [comment]
Never mind. Let’s just assume this is transient unless it happens again
